version: "3.8"
services:
  api-app:
    build: 
        context: "."
    env_file: ./.env
    restart: unless-stopped
    environment:
      - OPENAI_KEY=$OPENAI_KEY
      #   DB_HOST: mysql
      # ports:
      #   - "2000:3000"
    command: python app.py
volumes:
  db: