version: "3.8"
services:
  ask_my_doc_service:
    build: 
        context: "."
    env_file: ./.env
    environment:
      - OPENAI_API_KEY=$OPENAI_KEY
      - API_PORT=3000
      # - API_HOST="0.0.0.0"
    ports:
      - "3000:3000"
    # command: python app.py
volumes:
  db: