version: "3.8"
services:
  ask_my_doc_service:
    build: 
        context: "."
    env_file: ./.env
    environment:
      - OPENAI_KEY=$OPENAI_KEY
      #   DB_HOST: mysql
      # ports:
      #   - "2000:3000"
    # command: python app.py
volumes:
  db: